### ISSUE TITLE
Using Patterns, item tooltip shows price of 0

### ISSUE THREAD

**Issue by elliottmb** [Dandielo/DtlCitizensTrader#29]
In setting up our server's traders, we wanted to take advantage of the pattern system. While the documentation on the wiki is a bit unclear at times, I don't think what we're experiencing is normal.

Here's one of our test patterns:

``` yaml
test:
  prices:
    all:
      multiplier: 1.0
      '1': 1.0
      '3': 0.5
    buy:
      multiplier: 0.8
  items:
    all:
    - 1 a:1
    - 3 a:1
```

And here's what we're experiencing:

![2013-01-09_17 34 32](https://f.cloud.github.com/assets/2555214/55132/3a99df6c-5ab5-11e2-8091-e00396133d2c.png)
![2013-01-09_17 34 35](https://f.cloud.github.com/assets/2555214/55133/3ac81ac6-5ab5-11e2-8604-1d83f8a9e1b5.png)
![2013-01-09_17 34 38](https://f.cloud.github.com/assets/2555214/55134/3b3b8f38-5ab5-11e2-90a7-de9450c77870.png)
![2013-01-09_17 34 41](https://f.cloud.github.com/assets/2555214/55135/3b55c70e-5ab5-11e2-8b30-25734e4a71c2.png)

If you look at the screen shots, the price shows fine when hovering over the stock. However, when you hover over your own inventory, the info is zeroed out. Purchasing and selling works as expected. So really seems to be that in your code, you're not looking for the pattern price, but the one set to that trader. Since it's not defined outside of the pattern, it's zeroed.
