### ISSUE TITLE
Using inheritance increases multiplier

### ISSUE THREAD

**Issue by elliottmb** [Dandielo/DtlCitizensTrader#31]
I've found an interesting bug. If you inherit prices that have a multiplier, it is applied twice. If you then inherit something else, it's applied yet another time. If you ad the multiplier in the final set, it doesn't apply to the inherited.

``` yaml
land:
  prices:
    all:
      multiplier: 1.0
      '1': 1.0
      '3': 0.5
      '12': 0.5
      '13': 2.0
      '24': 1.5
    buy:
      multiplier: 0.8
nether:
  prices:
    all:
      multiplier: 1.0
      '87': 1.0
      '88': 2.0
    buy:
      multiplier: 0.8
test:
  inherits:
    - land
    - nether
  items:
    all:
    - 1 a:1
    - 3 a:1
    - 12 a:1
    - 13 a:1
    - 24 a:1
    - 87 a:1
    - 88 a:1
```

Buy multiplier ends up being 0.64 on some items

``````
```yaml
land:
  prices:
    all:
      multiplier: 1.0
      '1': 1.0
      '3': 0.5
      '12': 0.5
      '13': 2.0
      '24': 1.5
nether:
  prices:
    all:
      multiplier: 1.0
      '87': 1.0
      '88': 2.0
test:
  inherits:
    - land
    - nether
  prices:
    buy:
      multiplier: 0.8
  items:
    all:
    - 1 a:1
    - 3 a:1
    - 12 a:1
    - 13 a:1
    - 24 a:1
    - 87 a:1
    - 88 a:1
``````

Doesn't change a thing.
